mix.exs
- When using credo as dependency only on test environent in an app that has http-clients as a dependency, we get the following error:
```ex
Dependencies have diverged:
* credo (Hex package)
the :only option for dependency credo
> In mix.exs:
{:credo, "~> 1.5", [env: :prod, repo: "hexpm", hex: "credo", only: :test]}
does not match the :only option calculated for
> In deps/http_clients/mix.exs:
{:credo, "~> 1.5", [env: :prod, repo: "hexpm", hex: "credo"]}
Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```
- configures credo to be a dependency only on test environment
- n/a
- …
=> [SPRF-817] configures credo as dep only to test env

lib/http_clients/underwriter.ex, lib/http_clients/underwriter/proponent.ex, test/http_clients/underwriter_test.exs
- We need to create proponents through a POST request to the underwriter service.
- Implements the create_proponent method
- Creates underwriter client
- Tests
- N/A
- [[http-clients] Suportar POST /proponents no client do Underwriter](https://bcredi.atlassian.net/browse/SPRF-808)
=> [SPRF-808] Add function to create proponents using underwriter`s API

lib/http_clients/underwriter.ex, test/http_clients/underwriter_test.exs
- We need to consume underwriter API to get the proponent.
- Create get_proponent for Underwriter client
- n/a
- [SPRF-827](https://bcredi.atlassian.net/browse/SPRF-827)
=> [SPRF-827] Add get_proponent for underwriter client

lib/http_clients/underwriter/proponent.ex
- To retrieve the proponent`s serial_id from underwriter
- Adds serial_id to the struct
- N/A
- [SPRF-838](https://bcredi.atlassian.net/browse/SPRF-838)
=> [SPRF-838] adds serial_id to proponent struct

lib/http_clients/neurotech.ex, test/http_clients/neurotech_test.exs
- To support the homologation environment of SCR Bacen.
- Add base_date opts to Neurotech.compute_bacen_score/5.
- N/A
- [SPRF-840](https://bcredi.atlassian.net/browse/SPRF-840)
=> [SPRF-840] add base_date opts to Neurotech.compute_bacen_score/5

lib/http_clients/neurotech.ex
- Our function to format date is not ideal and might be wrong. Using Calendar to parse date instead
- Uses Calendar to parse date 
- N/A
- [corrigir formatação de data](https://bcredi.atlassian.net/browse/SPRF-843)
=> [SPRF-843] using Calendar to format date

lib/http_clients/underwriter.ex, test/http_clients/underwriter_test.exs
- To support the new "Update Proponent" route on Underwriter.
- Add `Underwriter.update_proponent/2`.
- N/A
- [SPRF-863](https://bcredi.atlassian.net/browse/SPRF-863)
=> [SPRF-863] add Underwriter.update_proponent/2

lib/http_clients/underwriter.ex, test/http_clients/underwriter_test.exs
- To fix #10 new function.
- Change spec to `:ok`.
- N/A
=> fix HttpClients.Underwriter.remove_proponent/2 spec

.github/workflows/elixir.yml, lib/http_clients/customer_management.ex, test/http_clients/customer_management_test.exs
- To support new Main Proponent identity validation flow. PoliciesExecutor needs to retrieve the proposal_id from a proponent_id.
- Add `get_proponent/2` on `HttpClients.CustomerManagement`;
- Fix CI cache :rocket: 
- N/A
- [SPRF-1014](https://bcredi.atlassian.net/browse/SPRF-1014)
=> [SPRF-1014] add "GET /v1/proponents/:id" route for CustomerManagement

README.md, lib/http_clients/neurotech/request.ex, test/http_clients/neurotech/request_test.exs
- To support running identity validation for Main Proponent. This fix is needed to support the Neurotech client with Hackney adapter.
- Fix Tesla `opts` on `HttpClients.Neurotech.Request`;
- Improve README.md
- N/A
- [SPRF-979](https://bcredi.atlassian.net/browse/SPRF-979)
=> [SPRF-979] Fix HttpClients.Neurotech.Request timeout config

lib/http_clients/scr_authorizer.ex, lib/http_clients/scr_authorizer/proponent_authorization.ex, test/http_clients/scr_authorizer_test.exs
- We need to create proponent authorizations through a POST request to the SCR Authorizer service.
- create %ProponentAuthorization{};
- create SCR Authorizer client;
- N/A
- [[http-clients] rota POST /v1/proponent_authorizations do scr-authorizer e documentar](https://bcredi.atlassian.net/browse/SPRF-968)
=> [SPRF-968] - Add scr authorizer client and proponent authorization

lib/http_clients/underwriter.ex, lib/http_clients/underwriter/proposal.ex, test/http_clients/underwriter_test.exs
- To support new proposal reopen flow. `Underwriter` needs to upsert proposal to publish the `underwriter.proposal.stage_changed` event.
- Add `update_proposal` on `HttpClients.Underwriter`
- n/a
- [ORG-1782](https://bcredi.atlassian.net/browse/ORG-1782)
=> [ORG-1782] Add "PUT /v1/proposals/:id" route for Underwriter

lib/http_clients/salesforce_token_server.ex, test/http_clients/salesforce_token_server_test.exs
- To support using SalesforceTokenServer name instead of PID.
- Changes `HttpClients.SalesforceTokenServer` function headers.
- N/A
- [SPRF-1097](https://bcredi.atlassian.net/browse/SPRF-1097)
=> [SPRF-1097] fix SalesforceTokenServer function headers

lib/http_clients/neurotech.ex, test/http_clients/neurotech_test.exs
- To support multiple originators on bacen_score policy request.
- The first commit is a refactor of the current tests (labels and order - fails first, then success cases), maybe start the review by them?
- Add `bacen_source` option to `Neurotech.compute_bacen_score/5`;
- N/A
- [SPRF-1107](https://bcredi.atlassian.net/browse/SPRF-1107)
=> [SPRF-1107] add bacen_source option to Neurotech.compute_bacen_score/5

lib/http_clients/salesforce_token_server.ex
- To compile `http-clients` when the app doesn't need to use the ExForce.
- Compile `HttpClients.SalesforceTokenServer` only when ExForce is present.
-N/A
=> fix HttpClients.SalesforceTokenServer when app don't need it

lib/http_clients/creditas/person_api.ex, lib/http_clients/creditas/person_api/address.ex, lib/http_clients/creditas/person_api/contact.ex, lib/http_clients/creditas/person_api/main_document.ex, lib/http_clients/creditas/person_api/person.ex, test/http_clients/creditas/person_api_test.exs
- To make requests to the creditas person api
- Creates the person api client
- Creates the person and related structures
- [[http-clients] criar structs e Creditas.PersonAPI.client/2](https://bcredi.atlassian.net/browse/SPRF-1119)
=> [SPRF-1119] Creditas person structs and client

lib/http_clients/creditas/person_api.ex, lib/http_clients/creditas/person_api/address.ex, lib/http_clients/creditas/person_api/contact.ex, lib/http_clients/creditas/person_api/person.ex, test/http_clients/creditas/person_api_test.exs
- To use the function to request persons on creditas-acl
- Implements the function and tests for the `GET person` on creditas person api
- [[http-clients] rota PersonAPI - GET person](https://bcredi.atlassian.net/browse/SPRF-1120)
=> [SPRF-1120] Function to get person on creditas person client

lib/http_clients/creditas/person_api.ex, lib/http_clients/creditas/person_api/person.ex, test/http_clients/creditas/person_api_test.exs
- To use the function to create persons on creditas-acl
- Implements the function and tests for the POST person on creditas person API
- n/a
- [SPRF-1121](https://bcredi.atlassian.net/browse/SPRF-1121)
=> [SPRF-1121] Create a person on Creditas API

lib/http_clients/creditas/person_api.ex, test/http_clients/creditas/person_api_test.exs
Please enter the commit message for your changes. Lines starting
- Using the person struct on the creation request sends some keys not accepted by the creation API.
- Accepts attrs as a map to create person
- [SPRF-1124](https://bcredi.atlassian.net/browse/SPRF-1124)
=> [SPRF-1124] accept person as a map for creation

.github/workflows/elixir.yml, lib/http_clients/neurotech.ex, test/http_clients/fixtures/neurotech.ex, test/http_clients/neurotech_test.exs
- We can't try parse a nil to integer, so we have to check it before.
- If neurotech return isn't a binary (string), then returns 0;
- `mix deps.update http_client` mainly in `bacen-scoring` service
- [Tratar retorno nulo neurotech](https://bcredi.atlassian.net/browse/SPRF-1019)
=> [SPRF0-1019] - Fix string to integer when return is empty

lib/http_clients/creditas/person_api.ex, lib/http_clients/creditas/person_api/address.ex, test/http_clients/creditas/person_api_test.exs
- When creating an loan, we need the person to have administrative area level fields filled with city and state
- Accepts administrativeAreaLevel 1 and 2 for state and city
- [[http-clients e crm-acl] Adicionar cidade e estado no endereço da pessoa](https://bcredi.atlassian.net/browse/SPRG-1168)
=> [SPRF-1168] Adds state and city to person

lib/http_clients/underwriter.ex, test/http_clients/underwriter_test.exs
- To support the new route.
- Add `Underwriter.get_main_proponent/2`;
- N/A
- [SPRF-1243](https://bcredi.atlassian.net/browse/SPRF-1243)
=> [SPRF-1243] add Underwriter.get_main_proponent/2

lib/http_clients/underwriter.ex, test/http_clients/underwriter_test.exs
- We need to get proposals on underwriter to adapt the qualification flow
- Adds function to get proposals on underwriter
- [SPRF-1249](https://bcredi.atlassian.net/browse/SPRF-1249)
=> [SPRF-1249] Function to get underwriter proposal

lib/http_clients/underwriter.ex, lib/http_clients/underwriter/credit_analysis.ex, lib/http_clients/underwriter/partner.ex, lib/http_clients/underwriter/proponent.ex, lib/http_clients/underwriter/proposal.ex, lib/http_clients/underwriter/proposal_simulation.ex, test/http_clients/underwriter_test.exs
- New fields need to be added to the underwriter API so we can qualify proposals
- Adds the missing fields for qualification on Underwriter.Proposal
- [SPRF-1249](https://bcredi.atlassian.net/browse/SPRF-1249)
=> [SPRF-1249] adds fields to underwriter proposal

lib/http_clients/neurotech.ex, test/http_clients/fixtures/neurotech.ex, test/http_clients/neurotech_test.exs
- To not disapprove a Proponent's identity when `Receita Federal` is down.
- Fix `HttpClients.Neurotech.check_identity/4` response.
- [SPRF-1318](https://bcredi.atlassian.net/browse/SPRF-1318)
=> [SPRF-1318] fix HttpClients.Neurotech.check_identity/4 response when Receita Federal failed

lib/http_clients/creditas/person_deletion_api.ex, test/http_clients/creditas/person_deletion_api_test.exs
- To support "Client Anonymization" flow.
- Add PersonDeletionApi client function.
- N/A
- [SPRF-1314](https://bcredi.atlassian.net/browse/SPRF-1314)
=> [SPRF-1314] add PersonDeletionApi client
